# Generated by Django 5.1.6 on 2025-03-02 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="alt_test",
            new_name="alt_text",
        ),
        migrations.AlterField(
            model_name="price",
            name="retail_pay_type",
            field=models.CharField(
                choices=[
                    ("kg", "Kg"),
                    ("g", "Gram"),
                    ("pcs", "Pcs"),
                    ("Sets", "Set"),
                    ("Dozen", "Dozen"),
                ],
                default="pcs",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="wholesale_pay_type",
            field=models.CharField(
                choices=[
                    ("kg", "Kg"),
                    ("g", "Gram"),
                    ("pcs", "Pcs"),
                    ("Sets", "Set"),
                    ("Dozen", "Dozen"),
                ],
                default="pcs",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_type",
            field=models.CharField(
                choices=[
                    ("kg", "Kg"),
                    ("g", "Gram"),
                    ("pcs", "Pcs"),
                    ("Sets", "Set"),
                    ("Dozen", "Dozen"),
                ],
                default="pcs",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CategoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="category_images/")),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categoryimages",
                        to="business.productcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Images",
            },
        ),
    ]
