# Generated by Django 5.1.6 on 2025-03-02 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_rename_alt_test_productimage_alt_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryimage",
            name="product_category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categoryimages",
                to="business.productcategory",
            ),
        ),
    ]
