# Generated by Django 5.1.6 on 2025-02-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_order_approved_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discount",
            options={"verbose_name_plural": "Discounts"},
        ),
        migrations.AlterModelOptions(
            name="exchangerate",
            options={"verbose_name_plural": "Exchange Rates"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name_plural": "Order Items"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name_plural": "Product Categories"},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={"verbose_name_plural": "Product Images"},
        ),
        migrations.AddField(
            model_name="product",
            name="description_jp",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_jp",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
