# Generated by Django 5.1.6 on 2025-02-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0005_remove_product_price_price_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight_type",
            field=models.CharField(
                choices=[("kg", "Kg"), ("Gram", "G")], default="kg", max_length=20
            ),
        ),
    ]
