# Generated by Django 5.1.6 on 2025-02-24 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0006_product_description_en_product_name_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="discount_percentage",
        ),
        migrations.AddField(
            model_name="discount",
            name="retail_discount_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="wholesale_discount_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="retail_pay_type",
            field=models.CharField(
                choices=[("Kilograms", "Kg"), ("Grams", "Gram"), ("Pieces", "Pcs")],
                default="Pieces",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="wholesale_pay_type",
            field=models.CharField(
                choices=[("Kilograms", "Kg"), ("Grams", "Gram"), ("Pieces", "Pcs")],
                default="Pieces",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="business.product",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="business.product",
            ),
        ),
    ]
