# Generated by Django 5.1.6 on 2025-02-26 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0008_alter_price_retail_pay_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={"verbose_name_plural": "Prices"},
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Order Confimed by Customer", "Confirmed"),
                    ("Order Approved by Moderator", "Approved"),
                    ("Order Completed", "Completed"),
                    ("Order Cancelled", "Cancelled"),
                ],
                default="Order Confimed by Customer",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="UserCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Carts",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("retail_type", models.BooleanField(default=True)),
                ("quantity", models.PositiveIntegerField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.product",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="business.usercart",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cart Items",
                "unique_together": {("cart", "product")},
            },
        ),
    ]
